name: Deploy Cloudformation

on:
  push:
    paths:
      - "cloudformation/template.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Deploy Stack

        run: |
          aws cloudformation deploy \
              --template-file cloudformation/template.yaml \
              --stack-name demo-stack \
              --capabilities CAPABILITY_NAMED_IAM

      - name: Upload File

        run: |
          aws s3 cp files/A_Billion_Wicked_Thoughts.pdf s3://kaushik-demo-cf-bucket-70025
